# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  testing:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest test.py

  build:
    runs-on: self-hosted
    needs: testing
    steps:
      - name: Docker build
        run: |
          docker --debug build -t "flask_testing" .
          docker run -d --name test -p 5000:5000 flask_testing
      
